version: 2
updates:
  # npm パッケージの監視
  - package-ecosystem: "npm"
    directory: "/packages/web-app-vercel"
    schedule:
      interval: "weekly"
      time: "10:00"
      timezone: "Asia/Tokyo"
    reviewers:
      - "is0692vs"
    open-pull-requests-limit: 10
    groups:
      npm-dependencies:
        patterns:
          - "*"

  # GitHub Actionsの監視
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "10:00"
      timezone: "Asia/Tokyo"
    reviewers:
      - "is0692vs"
    groups:
      actions-dependencies:
        patterns:
          - "*"
